apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8.0.31
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: ""
        - name : MYSQL_ALLOW_EMPTY_PASSWORD
        - name : MYSQL_DATABASE
          value: blog
        - name : MYSQL_USR
          value : root
        ports:
        - containerPort: 3306
